version: '3'

tasks:
  default:
    desc: Show this help message
    silent: true
    cmds:
      - task --list

  install:
    desc: Install dependencies
    silent: true
    cmds:
      - echo "Installing dependencies..."
      - cmd: npm install
        silent: true

  server:
    desc: Run the server in development mode
    silent: true
    cmds:
      - echo "Starting server..."
      - cmd: npx nx serve server
        silent: true

  client:
    desc: Run the client in development mode
    silent: true
    cmds:
      - echo "Starting client..."
      - cmd: npx nx serve client
        silent: true

  run:
    desc: Run both server and client in parallel (automatically starts PostgreSQL)
    silent: true
    cmds:
      - echo "Starting server and client..."
      - echo "Note - PostgreSQL will be started automatically if not running"
      - cmd: npx nx run-many --target=serve --projects=server,client --parallel=2
        silent: true

  all:
    desc: Alias for run (starts both server and client)
    silent: true
    cmds:
      - task run

  kill:
    desc: Kill all running server and client processes
    silent: true
    cmds:
      - echo "Stopping all services..."
      - cmd: pkill -f "nx serve server" || true
        silent: true
      - cmd: pkill -f "nx serve client" || true
        silent: true
      - cmd: pkill -f "webpack-cli" || true
        silent: true
      - cmd: bash -c 'lsof -ti :3000 2>/dev/null | xargs kill -9 2>/dev/null || true'
        silent: true
      - cmd: bash -c 'lsof -ti :4200 2>/dev/null | xargs kill -9 2>/dev/null || true'
        silent: true
      - echo "All services stopped"

  run-many:
    desc: Run a target on multiple projects
    summary: |
      Usage: task run-many TARGET=<target> [PROJECTS=<projects>]
      Examples:
        task run-many TARGET=test PROJECTS=server,client
        task run-many TARGET=build
    cmds:
      - |
        if [ -z "{{.TARGET}}" ]; then
          echo "Usage: task run-many TARGET=<target> [PROJECTS=<project1,project2>]"
          echo "Example: task run-many TARGET=test PROJECTS=server,client"
          echo "Example: task run-many TARGET=build"
          exit 1
        fi
        if [ -z "{{.PROJECTS}}" ]; then
          echo "Running target {{.TARGET}} on all projects..."
          npx nx run-many --target={{.TARGET}} --all
        else
          echo "Running target {{.TARGET}} on projects: {{.PROJECTS}}..."
          npx nx run-many --target={{.TARGET}} --projects={{.PROJECTS}}
        fi
    silent: true

  test:
    desc: Run all tests
    silent: true
    cmds:
      - echo "Running all tests..."
      - cmd: npx nx run-many --target=test --all
        silent: true

  test-server:
    desc: Run server tests
    silent: true
    cmds:
      - echo "Running server tests..."
      - cmd: npx nx test server
        silent: true

  test-client:
    desc: Run client tests
    silent: true
    cmds:
      - echo "Running client tests..."
      - cmd: npx nx test client
        silent: true

  e2e:
    desc: Run all e2e tests
    silent: true
    cmds:
      - echo "Running all e2e tests..."
      - cmd: npx nx run-many --target=e2e --all
        silent: true

  e2e-client:
    desc: Run client e2e tests
    silent: true
    cmds:
      - echo "Running client e2e tests..."
      - cmd: npx nx e2e client-e2e
        silent: true

  e2e-server:
    desc: Run server e2e tests
    silent: true
    cmds:
      - echo "Running server e2e tests..."
      - cmd: npx nx e2e server-e2e
        silent: true

  build:
    desc: Build all projects
    silent: true
    cmds:
      - echo "Building all projects..."
      - cmd: npx nx run-many --target=build --all
        silent: true

  build-server:
    desc: Build server
    silent: true
    cmds:
      - echo "Building server..."
      - cmd: npx nx build server
        silent: true

  build-client:
    desc: Build client
    silent: true
    cmds:
      - echo "Building client..."
      - cmd: npx nx build client
        silent: true

  lint:
    desc: Lint all projects
    silent: true
    cmds:
      - echo "Linting all projects..."
      - cmd: npx nx run-many --target=lint --all
        silent: true

  lint-server:
    desc: Lint server
    silent: true
    cmds:
      - echo "Linting server..."
      - cmd: npx nx lint server
        silent: true

  lint-client:
    desc: Lint client
    silent: true
    cmds:
      - echo "Linting client..."
      - cmd: npx nx lint client
        silent: true

  clean:
    desc: Clean build artifacts
    silent: true
    cmds:
      - echo "Cleaning build artifacts..."
      - cmd: rm -rf dist
        silent: true
      - cmd: rm -rf node_modules/.cache
        silent: true
      - cmd: npx nx reset
        silent: true
