/**
 * Interface representing a Todo item.
 * This is the core domain model shared between frontend and backend.
 * The 'I' prefix is a common convention for interfaces in TypeScript.
 */
export interface ITodo {
  /** Unique identifier for the todo item */
  id: string;
  /** Title of the todo item */
  title: string;
  /** Description or details of the todo item */
  description: string;
  /** Whether the todo item has been completed */
  completed: boolean;
}

/**
 * Type for creating a new todo item.
 * 
 * Uses TypeScript's Pick utility type to select only 'title' and 'description' from ITodo.
 * The 'id' is excluded because it will be generated by the server.
 * The 'completed' is excluded because new todos always start as incomplete.
 * 
 * Example: { title: "Buy groceries", description: "Milk and bread" }
 */
export type ICreateTodo = Pick<ITodo, 'title' | 'description'>;

/**
 * Type for partially updating an existing todo item.
 * 
 * Uses two TypeScript utility types:
 * 1. Omit<ITodo, 'id'> - Removes 'id' from ITodo (can't change the ID)
 * 2. Partial<...> - Makes all remaining fields optional
 * 
 * This allows updating only specific fields without sending the entire object.
 * Example: { completed: true } - only update the completed status
 * Example: { title: "New title", description: "New description" }
 */
export type IUpdateTodo = Partial<Omit<ITodo, 'id'>>;

/**
 * Type for upserting (update or insert) a todo item.
 * 
 * This is the full ITodo interface, requiring all fields including 'id'.
 * Used for PUT operations that either:
 * - Replace an existing todo entirely if the ID exists
 * - Create a new todo with a specific ID if it doesn't exist
 * 
 * Example: { id: "123", title: "Task", description: "Details", completed: false }
 */
export type IUpsertTodo = ITodo;