import { ITodo } from './todo.interface';

/**
 * Interface representing a User in the system.
 * This is the core domain model shared between frontend and backend.
 */
export interface IUser {
  /** Randomly generated primary key (UUID) by the database */
  id: string;

  /**
   * We'll just use an email as a user identifier
   * instead of worrying about a username, or a
   * formal first/last name.
   */
  email: string;

  /**
   * This is **NOT** the user's actual password! Instead,
   * this property will contain a hash of the password
   * specified when the user signed up. An API should
   * never be storing the actual password, encrypted or
   * not.
   */
  password: string;

  /**
   * A single user will be associated with zero, one, or more
   * to-do items, which means this field should never be
   * `undefined`. The object will always contain an array,
   * even if empty.
   */
  todos: ITodo[];
}

/**
 * Type for creating a new user.
 *
 * Uses TypeScript's Pick utility type to select only 'email' and 'password' from IUser.
 * The 'id' is excluded because it will be generated by the database.
 * The 'todos' is excluded because new users start with an empty array.
 *
 * Example: { email: "user@example.com", password: "hashedPassword" }
 */
export type ICreateUser = Pick<IUser, 'email' | 'password'>;

/**
 * Type for partially updating an existing user.
 *
 * Uses two TypeScript utility types:
 * 1. Omit<IUser, 'id'> - Removes 'id' from IUser (can't change the ID)
 * 2. Partial<...> - Makes all remaining fields optional
 *
 * This allows updating only specific fields without sending the entire object.
 * Example: { email: "newemail@example.com" }
 */
export type IUpdateUser = Partial<Omit<IUser, 'id'>>;

/**
 * Type for upserting (update or insert) a user.
 *
 * This is the full IUser interface, requiring all fields including 'id'.
 * Used for PUT operations that either:
 * - Replace an existing user entirely if the ID exists
 * - Create a new user with a specific ID if it doesn't exist
 *
 * Example: { id: "123", email: "user@example.com", password: "hashedPassword", todos: [] }
 */
export type IUpsertUser = IUser;

/**
 * Type representing public user data that can be safely exposed in API payloads.
 * This excludes the password field to prevent accidental exposure of sensitive information.
 *
 * This was added so that we can consistently know which User properties
 * will be exposed in API payloads.
 */
export type IPublicUserData = Omit<IUser, 'password'>;
