/**
 * Database Module
 *
 * This module is responsible for setting up TypeORM entities (database schemas) for the todo and user features.
 * It uses TypeOrmModule.forFeature() to register entity schemas that will be available for
 * dependency injection in other parts of the application.
 *
 * The key difference between forFeature() and forRoot():
 * - forRoot() is used once in the root AppModule to configure the database connection
 * - forFeature() is used in feature modules to register specific entities/schemas
 *
 * Since this is an independent module, TypeOrmModule is called with forFeature() instead of
 * forRoot() - a common pattern for NestJS modules. Our schemas will be imported here to ensure
 * their metadata is registered when the app is initialized.
 *
 * By exporting TypeOrmModule, we make the registered repositories available to any module
 * that imports DatabaseModule. This allows other modules (like feature modules) to inject
 * repositories using @InjectRepository() decorator.
 *
 * Why is TypeOrmModule exported? From NestJS docs: "If you want to use the repository outside
 * of the module which imports TypeOrmModule.forFeature(), you'll need to re-export the providers
 * generated by it."
 */
import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ToDoEntitySchema } from './database/schemas/to-do.entity-schema';
import { UserEntitySchema } from './database/schemas/user.entity-schema';

@Module({
  // Register the entity schemas so TypeORM knows about our table structures
  // Both ToDoEntitySchema and UserEntitySchema are registered here
  imports: [TypeOrmModule.forFeature([ToDoEntitySchema, UserEntitySchema])],

  // Export TypeOrmModule so other modules can use the repositories
  // This is necessary if you want to inject repositories outside of this module
  exports: [TypeOrmModule],
})
export class DatabaseModule {}
