/**
 * Database Module
 * 
 * This module is responsible for setting up TypeORM entities (database schemas) for the todo feature.
 * It uses TypeOrmModule.forFeature() to register entity schemas that will be available for
 * dependency injection in other parts of the application.
 * 
 * The key difference between forFeature() and forRoot():
 * - forRoot() is used once in the root AppModule to configure the database connection
 * - forFeature() is used in feature modules to register specific entities/schemas
 * 
 * Since this is an independent module, TypeOrmModule is called with forFeature() instead of
 * forRoot() - a common pattern for NestJS modules. Our schema will be imported here to ensure
 * its metadata is registered when the app is initialized.
 * 
 * By exporting TypeOrmModule, we make the registered repositories available to any module
 * that imports DatabaseModule. This allows other modules (like feature modules) to inject
 * repositories using @InjectRepository() decorator.
 * 
 * Why is TypeOrmModule exported? From NestJS docs: "If you want to use the repository outside
 * of the module which imports TypeOrmModule.forFeature(), you'll need to re-export the providers
 * generated by it."
 */
import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ToDoEntitySchema } from './database/schemas/to-do.entity-schema';

@Module({
  // Register the ToDoEntitySchema so TypeORM knows about our todo table structure
  imports: [TypeOrmModule.forFeature([ToDoEntitySchema])],
  
  // Export TypeOrmModule so other modules can use the todo repository
  // This is necessary if you want to inject repositories outside of this module
  exports: [TypeOrmModule],
})
export class DatabaseModule {}
