/**
 * Data Transfer Objects (DTOs) for User operations
 * 
 * DTOs are objects that define how data is structured when it's transferred
 * between different layers of an application (e.g., from client to server,
 * or from API to database). They serve multiple purposes:
 * 
 * 1. Validation: Ensure incoming data meets requirements before processing
 * 2. Documentation: Provide Swagger/OpenAPI documentation for API endpoints
 * 3. Type Safety: Enforce TypeScript types at runtime through decorators
 * 4. Data Transformation: Control what data is exposed/expected in different contexts
 * 
 * This file contains DTOs for:
 * - Creating new users (CreateUserDto)
 * - Returning users in API responses (UserResponseDto)
 */

// class-validator decorators: Validate data at runtime
import { IsEmail, IsNotEmpty, IsStrongPassword, IsString } from 'class-validator';

// @nestjs/swagger decorator: Generates OpenAPI/Swagger documentation
import { ApiProperty } from '@nestjs/swagger';

// Domain interfaces: The domain models that define the structure
import { ICreateUser, IPublicUserData } from '@full-stack-todo/shared/domain';
import { ITodo } from '@full-stack-todo/shared/domain';

/**
 * Data Transfer Object for creating a new user.
 * 
 * This DTO is used when a client wants to create a new user account.
 * It requires email and password because:
 * - The ID is auto-generated by the database (UUID)
 * - The todos array starts empty for new users
 * 
 * TypeScript: Implements ICreateUser to ensure type safety
 * 
 * Validation Strategy:
 * - Email must be a valid email format
 * - Password must meet strong password requirements
 * - Both fields are required
 * 
 * Usage: POST /api/v1/users
 */
export class CreateUserDto implements ICreateUser {
  /**
   * The user's email address, used as the unique identifier
   * 
   * Validation Rules:
   * - @IsEmail(): Must be a valid email format
   * - @IsNotEmpty(): Cannot be null, undefined, or an empty string
   * 
   * The `!` (non-null assertion) tells TypeScript this property will always
   * have a value after validation, even though it's not initialized in the class.
   */
  @ApiProperty({
    type: String,
    example: 'user@example.com',
    required: true,
    description: 'The user\'s email address, used as a unique identifier',
    format: 'email',
  })
  @IsEmail()
  @IsNotEmpty()
  email!: string;

  /**
   * The user's password (will be hashed before storage)
   * 
   * Validation Rules:
   * - @IsStrongPassword(): Must meet strong password requirements
   *   (minimum length, uppercase, lowercase, numbers, symbols)
   * - @IsNotEmpty(): Cannot be null, undefined, or an empty string
   * 
   * Note: The password will be hashed using bcrypt before being stored in the database.
   * The actual password is never stored in plain text.
   */
  @ApiProperty({
    type: String,
    example: 'SecureP@ssw0rd123!',
    required: true,
    description: 'The user\'s password (will be hashed before storage)',
    format: 'password',
  })
  @IsStrongPassword()
  @IsNotEmpty()
  password!: string;
}

/**
 * Data Transfer Object for returning user data in API responses.
 * 
 * This DTO represents public user data that can be safely exposed in API payloads.
 * It excludes the password field to prevent accidental exposure of sensitive information.
 * 
 * TypeScript: Implements IPublicUserData to ensure type safety and consistency
 * 
 * Usage: GET /api/v1/users/:id
 */
export class UserResponseDto implements IPublicUserData {
  /**
   * The unique identifier for the user (UUID)
   */
  @ApiProperty({
    type: String,
    example: '123e4567-e89b-12d3-a456-426614174000',
    required: true,
    description: 'The unique identifier for the user',
    format: 'uuid',
  })
  @IsString()
  @IsNotEmpty()
  id!: string;

  /**
   * The user's email address
   */
  @ApiProperty({
    type: String,
    example: 'user@example.com',
    required: true,
    description: 'The user\'s email address',
    format: 'email',
  })
  @IsEmail()
  @IsNotEmpty()
  email!: string;

  /**
   * Array of todos associated with this user
   * 
   * Note: This will always be an array, even if empty.
   * The todos are populated from the database relation.
   */
  @ApiProperty({
    type: Array,
    example: [],
    required: true,
    description: 'Array of todos associated with this user',
    isArray: true,
  })
  todos!: ITodo[];
}
