/**
 * Data Transfer Objects (DTOs) for Todo operations
 * 
 * DTOs are objects that define how data is structured when it's transferred
 * between different layers of an application (e.g., from client to server,
 * or from API to database). They serve multiple purposes:
 * 
 * 1. Validation: Ensure incoming data meets requirements before processing
 * 2. Documentation: Provide Swagger/OpenAPI documentation for API endpoints
 * 3. Type Safety: Enforce TypeScript types at runtime through decorators
 * 4. Data Transformation: Control what data is exposed/expected in different contexts
 * 
 * This file contains DTOs for:
 * - Creating new todos (CreateTodoDto)
 * - Updating existing todos (UpdateTodoDto)
 * - Upserting todos (create or update) (UpsertTodoDto)
 * - Returning todos in API responses (TodoDto)
 */

// class-validator decorators: Validate data at runtime
// - @IsString(): Ensures the value is a string
// - @IsNotEmpty(): Ensures the value is not empty (not null, undefined, or empty string)
// - @IsOptional(): Makes the field optional (can be undefined, but if provided must pass other validators)
// - @IsBoolean(): Ensures the value is a boolean
import { IsBoolean, IsNotEmpty, IsOptional, IsString } from 'class-validator';

// @nestjs/swagger decorator: Generates OpenAPI/Swagger documentation
// - @ApiProperty(): Documents the property in the API schema with type, examples, descriptions
import { ApiProperty } from '@nestjs/swagger';

// ITodo interface: The domain model that defines the structure of a todo item
import { ITodo } from '@full-stack-todo/shared/domain';

/**
 * Data Transfer Object for creating a new todo item.
 * 
 * This DTO is used when a client wants to create a new todo item.
 * It only requires the title and description because:
 * - The ID is auto-generated by the backend (typically a UUID)
 * - The completed status defaults to false for new todos
 * 
 * TypeScript Utility Types Used:
 * - `Pick<ITodo, 'title' | 'description'>`: Extracts only 'title' and 'description'
 *   from the ITodo interface, ensuring type safety while limiting what can be set
 * 
 * Validation Strategy:
 * - Both fields are required (no @IsOptional decorator)
 * - Both must be non-empty strings
 * - Validation happens automatically when this DTO is used with NestJS validation pipes
 * 
 * Usage: POST /api/todos
 */
export class CreateTodoDto implements Pick<ITodo, 'title' | 'description'> {
  /**
   * The title of the todo item
   * 
   * Validation Rules:
   * - @IsString(): Must be a string type
   * - @IsNotEmpty(): Cannot be null, undefined, or an empty string
   * 
   * The `!` (non-null assertion) tells TypeScript this property will always
   * have a value after validation, even though it's not initialized in the class.
   */
  @ApiProperty({
    type: String,
    example: 'Create a new blog post',
    required: true,
    description: 'The title of the todo item',
  })
  @IsString()
  @IsNotEmpty()
  title!: string;

  /**
   * The description of the todo item
   * 
   * Validation Rules:
   * - @IsString(): Must be a string type
   * - @IsNotEmpty(): Cannot be null, undefined, or an empty string
   */
  @ApiProperty({
    type: String,
    example: 'The Full Stack Engineer blog needs a new post!',
    required: true,
    description: 'Additional details about the todo item',
  })
  @IsString()
  @IsNotEmpty()
  description!: string;
}

/**
 * Data Transfer Object for upserting (create or update) a todo item.
 * 
 * "Upsert" means "update if exists, insert if not" - a common database operation.
 * This DTO requires all properties including the ID because:
 * - If the ID exists in the database, the todo will be updated
 * - If the ID doesn't exist, a new todo will be created with that ID
 * 
 * This is different from CreateTodoDto because:
 * - CreateTodoDto: Backend generates the ID automatically
 * - UpsertTodoDto: Client provides the ID (useful for syncing data from external sources)
 * 
 * TypeScript: Implements the full ITodo interface, ensuring all properties are present
 * 
 * Usage: PUT /api/todos/:id (where the ID in the body matches the URL parameter)
 */
export class UpsertTodoDto implements ITodo {
  /**
   * The unique identifier of the todo item
   * 
   * Required for upsert operations because the backend needs to know:
   * - Which todo to update (if it exists)
   * - What ID to use for creation (if it doesn't exist)
   * 
   * Typically a UUID (Universally Unique Identifier) format
   */
  @ApiProperty({
    type: String,
    example: '550e8400-e29b-41d4-a716-446655440000',
    required: true,
    description: 'The unique identifier of the todo item',
  })
  @IsString()
  @IsNotEmpty()
  id!: string;

  /**
   * The title of the todo item
   * Required for upsert operations
   */
  @ApiProperty({
    type: String,
    example: 'Update documentation',
    required: true,
    description: 'The title of the todo item',
  })
  @IsString()
  @IsNotEmpty()
  title!: string;

  /**
   * The description of the todo item
   * Required for upsert operations
   */
  @ApiProperty({
    type: String,
    example: 'Update the API documentation with new endpoints',
    required: true,
    description: 'Additional details about the todo item',
  })
  @IsString()
  @IsNotEmpty()
  description!: string;

  /**
   * The completion status of the todo item
   * 
   * @IsBoolean() ensures the value is a boolean (true or false)
   * @IsNotEmpty() ensures it's not null or undefined
   * 
   * Note: For booleans, @IsNotEmpty() is important because JavaScript treats
   * `false` as falsy, but we want to allow false as a valid value.
   */
  @ApiProperty({
    type: Boolean,
    example: false,
    required: true,
    description: 'Whether the todo item has been completed',
  })
  @IsBoolean()
  @IsNotEmpty()
  completed!: boolean;
}

/**
 * Data Transfer Object for updating an existing todo item.
 * 
 * This DTO supports partial updates - you can update one, some, or all fields
 * without needing to provide all properties. This is a common REST API pattern
 * that allows clients to send only the fields they want to change.
 * 
 * TypeScript Utility Types Explained:
 * - `Omit<ITodo, 'id'>`: Removes the 'id' property from ITodo (ID cannot be changed)
 * - `Partial<...>`: Makes all remaining properties optional
 * 
 * Result: All fields (title, description, completed) are optional, but ID is excluded
 * 
 * Validation Strategy:
 * - @IsOptional(): Field can be omitted from the request
 * - If provided, the field must still pass its type validator (@IsString, @IsBoolean)
 * - This allows clients to update just the title, or just completed status, etc.
 * 
 * Usage: PATCH /api/todos/:id (partial update) or PUT /api/todos/:id (full update)
 */
export class UpdateTodoDto implements Partial<Omit<ITodo, 'id'>> {
  /**
   * The title of the todo item
   * 
   * Optional field - can be omitted from the update request.
   * If provided, must be a non-empty string.
   * 
   * @IsOptional() allows the field to be undefined
   * @IsString() validates the type if the field is provided
   * 
   * Note: The `!` is still used because TypeScript needs to know the type,
   * but the value can be undefined at runtime until validation.
   */
  @ApiProperty({
    type: String,
    example: 'Updated title',
    required: false,
    description: 'The title of the todo item',
  })
  @IsString()
  @IsOptional()
  title!: string;

  /**
   * The description of the todo item
   * 
   * Optional field - can be omitted from the update request.
   * If provided, must be a non-empty string.
   */
  @ApiProperty({
    type: String,
    example: 'Updated description',
    required: false,
    description: 'Additional details about the todo item',
  })
  @IsString()
  @IsOptional()
  description!: string;

  /**
   * The completion status of the todo item
   * 
   * Optional field - can be omitted from the update request.
   * If provided, must be a boolean value.
   * 
   * Common use case: Toggle completion status without updating other fields
   * Example: PATCH /api/todos/123 { "completed": true }
   */
  @ApiProperty({
    type: Boolean,
    example: true,
    required: false,
    description: 'Whether the todo item has been completed',
  })
  @IsBoolean()
  @IsOptional()
  completed!: boolean;
}

/**
 * Data Transfer Object for Todo responses.
 * 
 * This DTO is used to document and type the response data returned from the API.
 * Unlike the other DTOs, this one doesn't have validation decorators because:
 * - It's used for OUTPUT (responses), not INPUT (requests)
 * - The data comes from the database/service layer, which is already validated
 * - Validation happens on input DTOs (CreateTodoDto, UpdateTodoDto, etc.)
 * 
 * Purpose:
 * - Swagger/OpenAPI documentation: Shows clients what to expect in API responses
 * - Type safety: Ensures response structure matches the ITodo interface
 * - Consistency: Guarantees all endpoints return todos in the same format
 * 
 * Usage: Returned by GET /api/todos, GET /api/todos/:id, POST /api/todos, etc.
 * 
 * Note: In NestJS, you can use this DTO with @ApiResponse() decorator on controllers
 * to document response types in Swagger UI.
 */
export class TodoDto implements ITodo {
  /**
   * The unique identifier of the todo item
   * Generated by the backend when the todo is created
   */
  @ApiProperty({
    type: String,
    example: '550e8400-e29b-41d4-a716-446655440000',
    description: 'The unique identifier of the todo item',
  })
  id!: string;

  /**
   * The title of the todo item
   * Set by the client when creating or updating the todo
   */
  @ApiProperty({
    type: String,
    example: 'Complete project documentation',
    description: 'The title of the todo item',
  })
  title!: string;

  /**
   * The description of the todo item
   * Provides additional context or details about what needs to be done
   */
  @ApiProperty({
    type: String,
    example: 'Write comprehensive documentation for all API endpoints',
    description: 'Additional details about the todo item',
  })
  description!: string;

  /**
   * The completion status of the todo item
   * 
   * - false: Todo is not yet completed (default for new todos)
   * - true: Todo has been marked as completed
   * 
   * Can be toggled via PATCH /api/todos/:id with { "completed": true/false }
   */
  @ApiProperty({
    type: Boolean,
    example: false,
    description: 'Whether the todo item has been completed',
  })
  completed!: boolean;
}

